In [2]:
import pandas as pd

- write a function where I can pass these files in, read them, convert header to lowercase, and values to lowercase

In [20]:
lou_inspection = pd.read_excel("louisville_inspection.xlsx")
lou_inspection.columns = lou_inspection.columns.str.lower()
lou_inspection = lou_inspection.applymap(lambda s: s.lower() if type(s) == str else s)
lou_inspection

,establishmentid,inspectionid,ins_typedesc,establishmentname,placename,address,address2,city,state,zip,typedescription,inspectiondate,score,grade,namesearch,intersection,objectid
0,29956,1684470,regular,cvs #6211,NaN,3721 lexington rd,NaN,louisville,ky,40207,pre-packaged retail,2022/07/06 00:00:00,100,NaN,cvs #6211,NaN,1
1,29967,1699737,regular,neighborhood food mart,NaN,542 lampton st,NaN,louisville,ky,40203,supermarket with processing,2022/09/07 00:00:00,97,NaN,neighborhood food mart,NaN,2
2,29979,1698679,regular,circle k #4700075,NaN,1630 arthur st,NaN,louisville,ky,40208,"retail-food 10,000 sq ft or less",2022/09/01 00:00:00,97,a,circle k #4700075,NaN,3
3,29979,1698680,regular,circle k #4700075,NaN,1630 arthur st,NaN,louisville,ky,40208,"retail-food 10,000 sq ft or less",2022/09/01 00:00:00,98,NaN,circle k #4700075,NaN,4
4,29979,1731827,regular,circle k #4700075,NaN,1630 arthur st,NaN,louisville,ky,40208,"retail-food 10,000 sq ft or less",2023/01/27 00:00:00,95,a,circle k #4700075,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11225,118688,1758428,other,gringos food trucks,NaN,NaN,NaN,louisville,ky,40202,self-contained mobile food units,2023/05/25 00:00:00,100,NaN,gringos food trucks,NaN,11226
11226,118697,1758467,other,frickled pickle express,NaN,NaN,NaN,louisville,ky,40202,self-contained mobile food units,2023/05/25 00:00:00,98,NaN,frickled pickle express,NaN,11227
11227,118710,1758790,other,tienda latinoamericano #3,NaN,8040 new lagrange rd,NaN,louisville,ky,40222,"retail-food 10,000 sq ft or less",2023/05/04 00:00:00,98,NaN,tienda latinoamericano #3,NaN,11228
11228,118710,1758791,other,tienda latinoamericano #3,NaN,8040 new lagrange rd,NaN,louisville,ky,40222,"retail-food 10,000 sq ft or less",2023/05/04 00:00:00,96,NaN,tienda latinoamericano #3,NaN,11229
11229,118711,1758835,other,trio sports bar and grill,NaN,4900 preston hwy,NaN,louisville,ky,40213,food service,2023/05/01 00:00:00,99,NaN,trio sports bar and grill,NaN,11230

In [21]:
yelp_df = pd.read_excel("yelp_places.xlsx")
yelp_df = yelp_df.applymap(lambda s: s.lower() if type(s) == str else s)
yelp_df

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,transactions,...,coordinates.latitude,coordinates.longitude,location.address1,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address
0,wi0imyhbxiy6am6gc7cfwg,hammerheads-louisville,hammerheads,https://s3-media1.fl.yelpcdn.com/bphoto/9ef0ls...,False,https://www.yelp.com/biz/hammerheads-louisvill...,1318,"[{'alias': 'southern', 'title': 'southern'}, {...",4.5,"['pickup', 'delivery']",...,38.238580,-85.736550,921 swan st,NaN,NaN,louisville,40204.0,us,ky,"['921 swan st', 'louisville, ky 40204']"
1,21nt4st1rxsutjsu9s5u4w,the-eagle-louisville-2,the eagle,https://s3-media2.fl.yelpcdn.com/bphoto/jiawkv...,False,https://www.yelp.com/biz/the-eagle-louisville-...,1501,"[{'alias': 'southern', 'title': 'southern'}, {...",4.5,['delivery'],...,38.234753,-85.714737,1314 bardstown rd,NaN,NaN,louisville,40204.0,us,ky,"['1314 bardstown rd', 'louisville, ky 40204']"
2,odtehpnf_efyedaos1tkbg,north-of-bourbon-louisville,north of bourbon,https://s3-media2.fl.yelpcdn.com/bphoto/vcbfow...,False,https://www.yelp.com/biz/north-of-bourbon-loui...,132,"[{'alias': 'diners', 'title': 'diners'}, {'ali...",4.5,[],...,38.229700,-85.738690,935 goss ave,NaN,NaN,louisville,40217.0,us,ky,"['935 goss ave', 'louisville, ky 40217']"
3,ip1u6lnesn-coxw9h0j0da,doc-crows-southern-smokehouse-and-raw-bar-loui...,doc crow's,https://s3-media2.fl.yelpcdn.com/bphoto/cucwgg...,False,https://www.yelp.com/biz/doc-crows-southern-sm...,2010,"[{'alias': 'southern', 'title': 'southern'}, {...",4.0,"['pickup', 'delivery']",...,38.256488,-85.752782,127 w main st,NaN,NaN,louisville,40202.0,us,ky,"['127 w main st', 'louisville, ky 40202']"
4,9mn8qellyejdr4l_ufp2lw,copper-and-kings-rooftop-bar-and-restaurant-lo...,copper & kings rooftop bar & restaurant,https://s3-media4.fl.yelpcdn.com/bphoto/sw2_kj...,False,https://www.yelp.com/biz/copper-and-kings-roof...,118,"[{'alias': 'cocktailbars', 'title': 'cocktail ...",4.5,['delivery'],...,38.257100,-85.730410,1121 e washington st,NaN,copper and kings,louisville,40206.0,us,ky,"['1121 e washington st', 'copper and kings', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,p4acvxz9mosyywpqtpjteg,thelmas-deli-louisville,thelma's deli,https://s3-media3.fl.yelpcdn.com/bphoto/he1s_s...,False,https://www.yelp.com/biz/thelmas-deli-louisvil...,28,"[{'alias': 'coffee', 'title': 'coffee & tea'},...",2.5,['delivery'],...,38.258010,-85.756740,140 n 4th st,NaN,galt house,louisville,40202.0,us,ky,"['140 n 4th st', 'galt house', 'louisville, ky..."
996,gbrx9_xc_oasfvqz_b5hhq,max-orient-louisville,max orient,https://s3-media2.fl.yelpcdn.com/bphoto/v4qj8w...,False,https://www.yelp.com/biz/max-orient-louisville...,21,"[{'alias': 'chinese', 'title': 'chinese'}]",4.0,['delivery'],...,38.140674,-85.669496,4801 outer lp,NaN,NaN,louisville,40219.0,us,ky,"['4801 outer lp', 'louisville, ky 40219']"
997,exwynwbnmx6fcu8snuf2rg,king-gyros-saint-matthews,king gyros,https://s3-media1.fl.yelpcdn.com/bphoto/ldc_ym...,False,https://www.yelp.com/biz/king-gyros-saint-matt...,16,"[{'alias': 'hotdogs', 'title': 'fast food'}, {...",4.0,"['delivery', 'pickup']",...,38.247116,-85.623725,5000 shelbyville rd,NaN,NaN,saint matthews,40207.0,us,ky,"['5000 shelbyville rd', 'saint matthews, ky 40..."
998,zmmrzwm1a6ndegv2fchxkg,diegos-mexican-grill-louisville,diego's mexican grill,https://s3-media2.fl.yelpcdn.com/bphoto/qbwy7v...,False,https://www.yelp.com/biz/diegos-mexican-grill-...,7,"[{'alias': 'mexican', 'title': 'mexican'}]",4.0,['delivery'],...,38.245490,-85.625189,5000 shelbyville rd,NaN,NaN,louisville,40207.0,us,ky,"['5000 shelbyville rd', 'louisville, ky 40207']"
999,bcgtatvxljvxmdephl0cpg,la-sierra-mexican-restaurant-louisville-4,la sierra mexican restaurant,https://s3-media2.fl.yelpcdn.com/bphoto/jwm4vd...,False,https://www.yelp.com/biz/la-sierra-mexican-res...,45,"[{'alias': 'mexican', 'title': 'mexican'}, {'a...",4.0,"['delivery', 'pickup']",...,38.154608,-85.658963,6501 shepherdsville rd 107,ste 107,NaN,louisville,40228.0,us,ky,"['6501 shepherdsville rd 107', 'ste 107', 'lou..."

In [12]:
joined = pd.concat([lou_inspection.rename(columns={'EstablishmentName':'name'}),yelp_df], ignore_index=True)
joined.to_excel("output.xlsx")

In [24]:
merged = pd.merge(lou_inspection,yelp_df, left_on=['establishmentname','address'], right_on=['name','location.address1'])
merged.to_excel("output.xlsx")